# Generated by Django 2.2.5 on 2019-09-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20190928_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdata',
            name='num_donations',
        ),
        migrations.AlterField(
            model_name='donationdata',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.DonationData')),
            ],
        ),
    ]
