# Generated by Django 2.2.5 on 2019-09-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdata',
            name='date',
            field=models.DateTimeField(verbose_name='date donated'),
        ),
    ]
