# Generated by Django 2.2.5 on 2019-09-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20190928_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
